---
name: "Reports"
guid: "d4312cd9-5c90-4f38-82e8-51da566790e8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-reports.png"
version: "11.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
owner: "jellyfin"
overview: "Generate reports of your media library"
description: "Generate reports of your media library"
category: "General"
artifacts:
  - "Jellyfin.Plugin.Reports.dll"
changelog: |
  changelog
